DROP TABLE user;
DROP TABLE photo;

CREATE TABLE IF NOT EXISTS user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(1024) NOT NULL UNIQUE,
    password_hash VARCHAR(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS photo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    owner_id INT NOT NULL,
    filename VARCHAR(1024) NOT NULL UNIQUE,
    category VARCHAR(1024) NOT NULL DEFAULT "",
    comment VARCHAR(1024) NOT NULL DEFAULT ""
);
